### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by Acmenwangtuo** [CancerDataScience/HistomicsML-TA#46]
When I run `python run_server_model` I get Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5: None -- [Errno 111] Connection refused
I0204 02:42:08.884776 140557407700800 cachefactory.py:148] Using python for large_image caching
Hoe can I  solve it

**Comment by slee172** [comment]
It seems like that fetching the model data from the URL is failed. The execution command "python run_server_model" automatically fetches the model data from the URL and then loads it to be used for. Can you download the model data from the URL? HistomicsML uses the model data form the Keras team, so you have to download the model data.

**Comment by Acmenwangtuo** [comment]
Thanks,I download it on local and upload to container the problem has been saved------------------ 原始邮件 ------------------
发件人: "Sanghoon Lee"<notifications@github.com>
发送时间: 2020年2月4日(星期二) 中午1:48
收件人: "CancerDataScience/HistomicsML-TA"<HistomicsML-TA@noreply.github.com>;
抄送: "Acmenwangtuo"<1198653145@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CancerDataScience/HistomicsML-TA] Connect error (#46)



It seems like that fetching the model data from the URL is failed. The execution command "python run_server_model" automatically fetches the model data from the URL and then loads it to be used for. Can you download the model data from the URL? HistomicsML uses the model data form the Keras team, so you have to download the model data.
 
&mdash;
