### ISSUE TITLE
Data import issue

### ISSUE THREAD

**Issue by slee172** [CancerDataScience/HistomicsML-TA#61]
@Reasat
I have finished creating the dataset and my project directory structure looks like this
![image](https://user-images.githubusercontent.com/15989033/95921549-189ace80-0d77-11eb-9a82-7e71564fda55.png)
I think I have to select 'myproject' as the base project 
However, I don't see the option in `http://localhost/HistomicsML/data.html`
![Screenshot from 2020-10-13 17-21-51](https://user-images.githubusercontent.com/15989033/95922374-c35fbc80-0d78-11eb-9ef5-cbf79f50dcbd.png)

**Comment by slee172** [comment]
I think this can be resolved by running the docker images on the correct directory. It seems like you "run" the docker on your home directory. I would suggest you to "run" the docker under the HistomicsML directory. The "Project directory" selection tab will search all directories under the "HistomicsML" directory.

**Comment by Reasat** [comment]
Thanks for opening this as a separate issue. 
I have run the docker under the HistomicsML directory. And I can locate the 'myproject' directory. And it automatically locates the slide_info.csv. But when I click submit it says, 
"localhost says 
Cannot create slide list"

**Comment by slee172** [comment]
@Reasat Good to hear that you confirmed the directory.

I think that the error text "Cannot create slide list" indicates that the system cannot create the "slidelist.txt" file under the "/datasets/myproject" directory. 

You may have to check two things.

1. slide_info.csv file is correct.
2. the "myproject" directory has a write permission.

You can refer to "Web server docker container needs a permission to access the directories: myproject1, myproject2, …, classifiers, so make sure that the directories support a writable permission (e.g. chmod 777 /master/myproject1)." in https://histomicsml2.readthedocs.io/en/latest/data-import.html

**Comment by Reasat** [comment]
Thanks! Allowing permission solved the import step. 
But in the next stage, I am facing this 
![Screenshot from 2020-10-13 21-53-44](https://user-images.githubusercontent.com/15989033/95938102-ccfc1b00-0d9e-11eb-94c0-39758b8a1408.png)
Note that in the generated slide_info.csv the location of the file is written down as `/datasets/myproject/tif/CMU-1-JP2K-33005.svs.dzi.tif` but the actual file name in the tif folder is `CMU-1-JP2K-33005.dzi.tif` (without svs). Tried with both filenames, but got the same error.

**Comment by slee172** [comment]
I think the Data Import issue has been resolved. 

I will move the issue of displaying a slide to another issue.
