### ISSUE TITLE
WSI files formats 

### ISSUE THREAD

**Issue by Reasat** [CancerDataScience/HistomicsML-TA#63]
The tutorials focus on transforming .svs files to tif. Are other files supported? For example .scn from leica scanners?
https://openslide.org/formats/leica/

Which part of the code should I modify to support .scn files?

**Comment by slee172** [comment]
@Reasat HistomicsML2 uses the IIP image server(https://iipimage.sourceforge.io/documentation/server/) to display multi-resolution TIFF formatted images. The SVS images can be converted to the TIFF by using a bash shell script.
You can find the bash shell script(create_tiff.sh) from here (https://histomicsml2.readthedocs.io/en/latest/data-create.html#download-the-dataset-creation-container). The 'create_tiff.sh' contains libvips in the code. So, you can test it following here https://libvips.github.io/libvips/
