### ISSUE TITLE
Purpose of converting the WSI into tif

### ISSUE THREAD

**Issue by Reasat** [CancerDataScience/HistomicsML-TA#69]
I am trying to understand the need for converting the wsi (say .svs) image to tif. https://histomicsml2.readthedocs.io/en/latest/data-create.html

I think the tiff file is used in plotting/zooming/panning in the UI. Is there a need for the conversion and saving of the files?
Is it possible to bypass this stage by using something equivalent to [this ](https://github.com/manzt/napari-lazy-openslide/blob/cd0aed6acca0bfbdcda8169de7605ae163a90f6a/napari_lazy_openslide/lazy_openslide.py#L133). Where the image is read by openslide and converted to zarr format. Seems in that way some disc space can be saved (since tiff files are not saved).

Since I am still trying to understand histomicsML interface, I may be missing important issues. Let me know if that's the case.

**Comment by slee172** [comment]
@Reasat HistomicsML2 is a fast interactive learning tool that enables users to select regions in WSIs over the web. The only reason we use the TIFF formatted is for the IIP image server which is designed for multi-resolution formats (TIFF or JPEG2000). They support URL-based access so that users can access the regions.

**Comment by cooperlab** [comment]
It has to do with the supporting the viewer. There are alternatives that would allow display directly from the native file format if supported by openslide, but this requires significant rework of several components. We would like to avoid this step in the future but there are other priorities we need to address first..
